"""v2 Phase D: behavior-cloned go-to-pose policy.

The dataset, model, and the BC training/closed-loop comparison are all CPU-fast and sim-only (no GL),
so everything here runs headless. One GL-guarded test drives the full autonomy loop on the learned policy.
"""

import json
import math

import numpy as np
import pytest

from feathersim.control.go_to_pose import PoseGains, drive_to_pose, velocity_command
from feathersim.policy.dataset import generate_dataset
from feathersim.policy.model import (
    ACTION_SCALE,
    PolicyMLP,
    denormalize_action,
    normalize_action,
)
from feathersim.policy.policy import PolicyController
from feathersim.policy.train import closed_loop_compare, train
from feathersim.sim.world import World


# --- dataset & model (pure) ----------------------------------------------------------------------


def test_dataset_actions_are_the_expert_controller():
    obs, actions = generate_dataset(n_samples=64, seed=0)
    assert obs.shape == (64, 3) and actions.shape == (64, 3)
    for o, a in zip(obs, actions):
        expert = velocity_command((0.0, 0.0, 0.0), tuple(o))
        assert np.allclose(a, expert, atol=1e-6)


def test_dataset_actions_within_velocity_limits():
    _, actions = generate_dataset(n_samples=256, seed=1)
    g = PoseGains()
    assert np.all(np.abs(actions[:, :2]) <= g.max_linear + 1e-6)
    assert np.all(np.abs(actions[:, 2]) <= g.max_angular + 1e-6)


def test_model_output_is_bounded_and_normalization_roundtrips():
    import torch

    out = PolicyMLP()(torch.randn(8, 3))
    assert out.shape == (8, 3) and torch.all(out.abs() <= 1.0)  # tanh head
    a = np.array([[0.5, -0.5, 1.0]], dtype=np.float32)
    assert np.allclose(denormalize_action(normalize_action(a)), a, atol=1e-6)


# --- behavior cloning learns the controller ------------------------------------------------------

# Train one policy for the module (≈5 s) and reuse it — closed-loop driving needs enough data to avoid
# compounding errors (offline val MSE is a poor predictor of it — see LEARNINGS.md), so not a tiny net.
@pytest.fixture(scope="module")
def trained_policy():
    obs, actions = generate_dataset(n_samples=12000, seed=0)
    return train(obs, actions, epochs=40, seed=0)


def test_bc_matches_expert_actions(trained_policy):
    model, val_mse = trained_policy
    assert val_mse < 5e-3  # learned the map tightly
    policy = PolicyController(model)
    rng = np.random.default_rng(7)
    errors = []
    for _ in range(50):
        pose = (rng.uniform(-1, 1), rng.uniform(-1, 1), rng.uniform(-math.pi, math.pi))
        target = (rng.uniform(-1, 1), rng.uniform(-1, 1), rng.uniform(-math.pi, math.pi))
        errors.append(np.abs(np.array(policy(pose, target)) - np.array(velocity_command(pose, target))))
    # Mean imitation error is small; the worst pointwise error is bounded (the tanh head can't fully
    # reach the controller's saturated ±max_angular, so allow more slack on the raw twist magnitude).
    assert np.mean(errors) < 0.08
    assert np.max(errors) < 0.35


def test_learned_policy_drives_to_goal(trained_policy):
    """A base driven by the learned policy reaches a goal pose (closed-loop, no controller)."""
    model, _ = trained_policy
    world = World(n_machines=1, seed=0, n_robots=1)
    world.set_base_pose(-1.0, 0.0, 0.0)
    result = drive_to_pose(world, (1.0, 0.5, 1.0), velocity_fn=PolicyController(model), max_steps=2000)
    assert result.reached


def test_learned_policy_honors_planning(trained_policy):
    """`Robot(plan=True, controller=policy)` drives the *planned* route on the learned policy too — the
    controller seam reaches through `follow_path`, not just the straight-line branch."""
    from feathersim.sdk.robot import Robot

    model, _ = trained_policy
    world = World(n_machines=3, seed=0, n_obstacles=2, n_robots=1)
    world.set_base_pose(0.0, 0.0, 0.0)
    robot = Robot(world, plan=True, controller=PolicyController(model))
    robot.move_to("machine_2")  # routes around the pillars, driven by the policy — raises if it can't
    gx, gy, _ = robot.tending_pose("machine_2")
    rx, ry, _ = robot.pose
    assert math.hypot(rx - gx, ry - gy) < 0.06


def test_closed_loop_policy_matches_expert(trained_policy):
    model, _ = trained_policy
    cmp = closed_loop_compare(PolicyController(model), n_episodes=12, seed=5)
    assert cmp["policy_reach"] >= cmp["expert_reach"] - 1e-9        # reaches as many goals as the expert
    assert cmp["policy_avg_steps"] <= cmp["expert_avg_steps"] * 1.3  # in comparable time


def test_committed_policy_metrics():
    """Lock the full-scale Phase-D headline from the committed artifact (regenerated by `make policy`)."""
    from feathersim.policy.train import METRICS_PATH

    m = json.loads(METRICS_PATH.read_text())
    assert m["val_mse"] < 5e-3
    assert m["policy_reach"] >= m["expert_reach"] - 1e-9
    assert m["policy_avg_steps"] <= m["expert_avg_steps"] * 1.3


# --- full autonomy loop on the learned policy (needs GL) -----------------------------------------


def _rendering_available() -> bool:
    import mujoco

    try:
        w = World(n_machines=1, seed=0)
        r = mujoco.Renderer(w.model, 32, 32)
        r.update_scene(w.data, w.machine_camera(0))
        r.render()
        r.close()
        return True
    except Exception:
        return False


@pytest.mark.skipif(
    not _rendering_available(),
    reason="MuJoCo rendering unavailable (set MUJOCO_GL=egl/osmesa on a headless host)",
)
def test_autonomy_loop_runs_on_learned_policy():
    import mujoco

    from feathersim.autonomy import run_autonomy
    from feathersim.perception.dataset import IMAGE_SIZE
    from feathersim.perception.infer import Perception
    from feathersim.perception.train import load_or_train_model
    from feathersim.policy.train import load_or_train_policy
    from feathersim.sdk.robot import Robot

    world = World(n_machines=3, seed=0, n_obstacles=0, n_robots=1)
    renderer = mujoco.Renderer(world.model, IMAGE_SIZE, IMAGE_SIZE)
    robot = Robot(world, controller=PolicyController(load_or_train_policy()))
    try:
        report = run_autonomy(world, Perception(load_or_train_model()), renderer, target_parts=3, robot=robot)
    finally:
        renderer.close()
    assert report.parts_delivered == 3  # the learned brain runs the whole loop
